// source: util/node_info_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var constants_pb = require('../constants_pb.js');
goog.object.extend(proto, constants_pb);
goog.exportSymbol('proto.wavesenterprise.NodeConfigResponse', null, global);
goog.exportSymbol('proto.wavesenterprise.NodeConfigResponse.BlockTimingCase', null, global);
goog.exportSymbol('proto.wavesenterprise.PoaRoundInfo', null, global);
goog.exportSymbol('proto.wavesenterprise.PosRoundInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wavesenterprise.NodeConfigResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.wavesenterprise.NodeConfigResponse.oneofGroups_);
};
goog.inherits(proto.wavesenterprise.NodeConfigResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wavesenterprise.NodeConfigResponse.displayName = 'proto.wavesenterprise.NodeConfigResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wavesenterprise.PoaRoundInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wavesenterprise.PoaRoundInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wavesenterprise.PoaRoundInfo.displayName = 'proto.wavesenterprise.PoaRoundInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wavesenterprise.PosRoundInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wavesenterprise.PosRoundInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wavesenterprise.PosRoundInfo.displayName = 'proto.wavesenterprise.PosRoundInfo';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.wavesenterprise.NodeConfigResponse.oneofGroups_ = [[101,102]];

/**
 * @enum {number}
 */
proto.wavesenterprise.NodeConfigResponse.BlockTimingCase = {
  BLOCK_TIMING_NOT_SET: 0,
  POA_ROUND_INFO: 101,
  POS_ROUND_INFO: 102
};

/**
 * @return {proto.wavesenterprise.NodeConfigResponse.BlockTimingCase}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getBlockTimingCase = function() {
  return /** @type {proto.wavesenterprise.NodeConfigResponse.BlockTimingCase} */(jspb.Message.computeOneofCase(this, proto.wavesenterprise.NodeConfigResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.wavesenterprise.NodeConfigResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wavesenterprise.NodeConfigResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wavesenterprise.NodeConfigResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cryptoType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    chainId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    consensus: jspb.Message.getFieldWithDefault(msg, 4, 0),
    minimumFeeMap: (f = msg.getMinimumFeeMap()) ? f.toObject(includeInstance, undefined) : [],
    additionalFeeMap: (f = msg.getAdditionalFeeMap()) ? f.toObject(includeInstance, undefined) : [],
    maxTransactionsInMicroBlock: jspb.Message.getFieldWithDefault(msg, 7, 0),
    minMicroBlockAge: (f = msg.getMinMicroBlockAge()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    microBlockInterval: (f = msg.getMicroBlockInterval()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    poaRoundInfo: (f = msg.getPoaRoundInfo()) && proto.wavesenterprise.PoaRoundInfo.toObject(includeInstance, f),
    posRoundInfo: (f = msg.getPosRoundInfo()) && proto.wavesenterprise.PosRoundInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wavesenterprise.NodeConfigResponse}
 */
proto.wavesenterprise.NodeConfigResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wavesenterprise.NodeConfigResponse;
  return proto.wavesenterprise.NodeConfigResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wavesenterprise.NodeConfigResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wavesenterprise.NodeConfigResponse}
 */
proto.wavesenterprise.NodeConfigResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {!proto.wavesenterprise.CryptoType} */ (reader.readEnum());
      msg.setCryptoType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChainId(value);
      break;
    case 4:
      var value = /** @type {!proto.wavesenterprise.ConsensusType} */ (reader.readEnum());
      msg.setConsensus(value);
      break;
    case 5:
      var value = msg.getMinimumFeeMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt64, null, "", 0);
         });
      break;
    case 6:
      var value = msg.getAdditionalFeeMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt64, null, "", 0);
         });
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxTransactionsInMicroBlock(value);
      break;
    case 8:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setMinMicroBlockAge(value);
      break;
    case 9:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setMicroBlockInterval(value);
      break;
    case 101:
      var value = new proto.wavesenterprise.PoaRoundInfo;
      reader.readMessage(value,proto.wavesenterprise.PoaRoundInfo.deserializeBinaryFromReader);
      msg.setPoaRoundInfo(value);
      break;
    case 102:
      var value = new proto.wavesenterprise.PosRoundInfo;
      reader.readMessage(value,proto.wavesenterprise.PosRoundInfo.deserializeBinaryFromReader);
      msg.setPosRoundInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wavesenterprise.NodeConfigResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wavesenterprise.NodeConfigResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wavesenterprise.NodeConfigResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCryptoType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getChainId();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getConsensus();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getMinimumFeeMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt64);
  }
  f = message.getAdditionalFeeMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt64);
  }
  f = message.getMaxTransactionsInMicroBlock();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getMinMicroBlockAge();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getMicroBlockInterval();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getPoaRoundInfo();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      proto.wavesenterprise.PoaRoundInfo.serializeBinaryToWriter
    );
  }
  f = message.getPosRoundInfo();
  if (f != null) {
    writer.writeMessage(
      102,
      f,
      proto.wavesenterprise.PosRoundInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string version = 1;
 * @return {string}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional CryptoType crypto_type = 2;
 * @return {!proto.wavesenterprise.CryptoType}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getCryptoType = function() {
  return /** @type {!proto.wavesenterprise.CryptoType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.wavesenterprise.CryptoType} value
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.setCryptoType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional int32 chain_id = 3;
 * @return {number}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getChainId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.setChainId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional ConsensusType consensus = 4;
 * @return {!proto.wavesenterprise.ConsensusType}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getConsensus = function() {
  return /** @type {!proto.wavesenterprise.ConsensusType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.wavesenterprise.ConsensusType} value
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.setConsensus = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * map<string, int64> minimum_fee = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getMinimumFeeMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.clearMinimumFeeMap = function() {
  this.getMinimumFeeMap().clear();
  return this;};


/**
 * map<string, int64> additional_fee = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getAdditionalFeeMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.clearAdditionalFeeMap = function() {
  this.getAdditionalFeeMap().clear();
  return this;};


/**
 * optional int32 max_transactions_in_micro_block = 7;
 * @return {number}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getMaxTransactionsInMicroBlock = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.setMaxTransactionsInMicroBlock = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional google.protobuf.Duration min_micro_block_age = 8;
 * @return {?proto.google.protobuf.Duration}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getMinMicroBlockAge = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 8));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
*/
proto.wavesenterprise.NodeConfigResponse.prototype.setMinMicroBlockAge = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.clearMinMicroBlockAge = function() {
  return this.setMinMicroBlockAge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.hasMinMicroBlockAge = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Duration micro_block_interval = 9;
 * @return {?proto.google.protobuf.Duration}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getMicroBlockInterval = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 9));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
*/
proto.wavesenterprise.NodeConfigResponse.prototype.setMicroBlockInterval = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.clearMicroBlockInterval = function() {
  return this.setMicroBlockInterval(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.hasMicroBlockInterval = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional PoaRoundInfo poa_round_info = 101;
 * @return {?proto.wavesenterprise.PoaRoundInfo}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getPoaRoundInfo = function() {
  return /** @type{?proto.wavesenterprise.PoaRoundInfo} */ (
    jspb.Message.getWrapperField(this, proto.wavesenterprise.PoaRoundInfo, 101));
};


/**
 * @param {?proto.wavesenterprise.PoaRoundInfo|undefined} value
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
*/
proto.wavesenterprise.NodeConfigResponse.prototype.setPoaRoundInfo = function(value) {
  return jspb.Message.setOneofWrapperField(this, 101, proto.wavesenterprise.NodeConfigResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.clearPoaRoundInfo = function() {
  return this.setPoaRoundInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.hasPoaRoundInfo = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * optional PosRoundInfo pos_round_info = 102;
 * @return {?proto.wavesenterprise.PosRoundInfo}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.getPosRoundInfo = function() {
  return /** @type{?proto.wavesenterprise.PosRoundInfo} */ (
    jspb.Message.getWrapperField(this, proto.wavesenterprise.PosRoundInfo, 102));
};


/**
 * @param {?proto.wavesenterprise.PosRoundInfo|undefined} value
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
*/
proto.wavesenterprise.NodeConfigResponse.prototype.setPosRoundInfo = function(value) {
  return jspb.Message.setOneofWrapperField(this, 102, proto.wavesenterprise.NodeConfigResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wavesenterprise.NodeConfigResponse} returns this
 */
proto.wavesenterprise.NodeConfigResponse.prototype.clearPosRoundInfo = function() {
  return this.setPosRoundInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wavesenterprise.NodeConfigResponse.prototype.hasPosRoundInfo = function() {
  return jspb.Message.getField(this, 102) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wavesenterprise.PoaRoundInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.wavesenterprise.PoaRoundInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wavesenterprise.PoaRoundInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wavesenterprise.PoaRoundInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    roundDuration: (f = msg.getRoundDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    syncDuration: (f = msg.getSyncDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wavesenterprise.PoaRoundInfo}
 */
proto.wavesenterprise.PoaRoundInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wavesenterprise.PoaRoundInfo;
  return proto.wavesenterprise.PoaRoundInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wavesenterprise.PoaRoundInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wavesenterprise.PoaRoundInfo}
 */
proto.wavesenterprise.PoaRoundInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRoundDuration(value);
      break;
    case 2:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setSyncDuration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wavesenterprise.PoaRoundInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wavesenterprise.PoaRoundInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wavesenterprise.PoaRoundInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wavesenterprise.PoaRoundInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoundDuration();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getSyncDuration();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Duration round_duration = 1;
 * @return {?proto.google.protobuf.Duration}
 */
proto.wavesenterprise.PoaRoundInfo.prototype.getRoundDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 1));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.wavesenterprise.PoaRoundInfo} returns this
*/
proto.wavesenterprise.PoaRoundInfo.prototype.setRoundDuration = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wavesenterprise.PoaRoundInfo} returns this
 */
proto.wavesenterprise.PoaRoundInfo.prototype.clearRoundDuration = function() {
  return this.setRoundDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wavesenterprise.PoaRoundInfo.prototype.hasRoundDuration = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Duration sync_duration = 2;
 * @return {?proto.google.protobuf.Duration}
 */
proto.wavesenterprise.PoaRoundInfo.prototype.getSyncDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 2));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.wavesenterprise.PoaRoundInfo} returns this
*/
proto.wavesenterprise.PoaRoundInfo.prototype.setSyncDuration = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wavesenterprise.PoaRoundInfo} returns this
 */
proto.wavesenterprise.PoaRoundInfo.prototype.clearSyncDuration = function() {
  return this.setSyncDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wavesenterprise.PoaRoundInfo.prototype.hasSyncDuration = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wavesenterprise.PosRoundInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.wavesenterprise.PosRoundInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wavesenterprise.PosRoundInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wavesenterprise.PosRoundInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    averageBlockDelay: (f = msg.getAverageBlockDelay()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wavesenterprise.PosRoundInfo}
 */
proto.wavesenterprise.PosRoundInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wavesenterprise.PosRoundInfo;
  return proto.wavesenterprise.PosRoundInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wavesenterprise.PosRoundInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wavesenterprise.PosRoundInfo}
 */
proto.wavesenterprise.PosRoundInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setAverageBlockDelay(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wavesenterprise.PosRoundInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wavesenterprise.PosRoundInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wavesenterprise.PosRoundInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wavesenterprise.PosRoundInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAverageBlockDelay();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Duration average_block_delay = 1;
 * @return {?proto.google.protobuf.Duration}
 */
proto.wavesenterprise.PosRoundInfo.prototype.getAverageBlockDelay = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 1));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.wavesenterprise.PosRoundInfo} returns this
*/
proto.wavesenterprise.PosRoundInfo.prototype.setAverageBlockDelay = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wavesenterprise.PosRoundInfo} returns this
 */
proto.wavesenterprise.PosRoundInfo.prototype.clearAverageBlockDelay = function() {
  return this.setAverageBlockDelay(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wavesenterprise.PosRoundInfo.prototype.hasAverageBlockDelay = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.wavesenterprise);
